### ISSUE TITLE
Bing keyword lookups only finding 6-10 search results

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#119]
I'm having some trouble with Bing only returning keyword position results if they're in the top 10. I suspect that the cookie value's attempt to set 50 results fails, thus returning the 'default' amount of somewhere between 6 and 10 results. If the rank isn't within that 6-10, then it's never found.

A search hasn't revealed any info about the cookie details changing for this, yet the standard values in the DB for the search engine don't seem to be working. This is what I have... is it accurate (yes this is for bing.com.au)?

URL: `http://www.bing.com/search?q=[--keyword--]&scope=web&first=[--start--]&setmkt=[--lang--]-au`
Cookie: `SRCHHPGUSR=NEWWND=0&NRSLT=50&SRCHLANG=[--lang--]`
50 | 1 | 50 | 50

**Comment by jas8522** [comment]
I added the NRSLT=50 cookie via Firefox inspector, then re-searched. I got 6 results on the first page, then 49 results on the second and all subsequent pages... @sendtogeo any idea how to get around the 6 results on the first page problem?

**Comment by sendtogeo** [comment]
Fixed and released with new version 4.2.0

**Comment by jas8522** [comment]
Awesome, thanks!
