### ISSUE TITLE
Throwing Error `Missing client_id ` while connecting to google

### ISSUE THREAD

**Issue by vivex** [seopanel/Seo-Panel#138]
Throwing folling error while trying to connect google connection 
```
Missing required parameter: client_id

````

**Comment by sendtogeo** [comment]
Hi Vivek,

Thanks for using seo panel.

Can you please update us, you have gone through following tutorial

http://docs.seopanel.in/user_guide/settings.html#google-oauth2-credentials

Looks like connection is not setup correctly.

Thanks for the support.

**Comment by sendtogeo** [comment]
Please update, if you face this issue again.
