### ISSUE TITLE
Responsive + Html5 design integration to seo panel

### ISSUE THREAD

**Issue by sendtogeo** [seopanel/Seo-Panel#14]
Responsive + Html5 design integration to seo panel

**Comment by AlexanderSk** [comment]
The new version actually introduced an extra theme with subscription though... http://blog.seopanel.in/tag/responsive-theme/

**Comment by sendtogeo** [comment]
Alex, It is actually a paid theme.  We plan to release a new free responsive theme for seo panel.

**Comment by sendtogeo** [comment]
Todo

1) check mail content after new design
2) Add changes to datepicker
3) Dashboard page table border issues
4) Translation of main menu Tools & Plugins
5) spacing issue in dashboard reports
6) In medium screen the top menu not looks good
