### ISSUE TITLE
No option in API to obtain list of search engines

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#147]
When using the API to interact with SEO panel, if you wish to add keywords to track for a website, you do this: 

```
action = createKeyword
name => The name of the keyword
website_id => The website id of keyword
searchengines => The search engine ids of the keyword - [id1:id2] Eg. 1:2
```

The problem is that it's expecting IDs of search engines to pass as the 'searchengines' parameter, however I can't find a way to obtain that list of search engine IDs from SEOPanel via the API. It would have to be a hard coded magic number.

There's two ways I can see to rectify this:

1. Add a getSearchEngines API function that returns the list of search engines
2. To avoid additional API calls, the list of search engines could instead be returned as part of the response to `getReportByWebsiteId`. Currently it already includes the list of *selected* search engines for each particular keyword. Perhaps it could also include the list of available search engines; probably prior or after the list of keywords.

Along similar lines, the getUserInfo action returns `utype_id` however there appears to be no way to get any data from user types/roles (like the max number of sites and keywords allowed). I suggest that the info for that particular utype_id should be returned along with the getUserInfo response data.

**Comment by sendtogeo** [comment]
Thanks for the notification. I have added it in new version of seo panel 4.3.0

Eg:

$paramList['category'] = "searchengine";
$paramList['action'] = "getSearchengines";
$paramList['status'] = 1;                // optional to fins active & inactive
$paramList['search'] = 'yahoo';     // optional to find search engines

**Comment by jas8522** [comment]
Awesome, thanks @sendtogeo !
