### ISSUE TITLE
Since Nov 21 2019, Google.com regex appears to have changed

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#153]
The new value that is working in my initial tests (needs more extensive testing) is:
```
<div.*?class="?g.*?><div class="r"><a href="(.*?)".*?><h3.*?><span.*?>(.*?)<\/span><\/h3>.*?<\/a>.*?<\/div><div class="s">.*<span class="st">(.*?)<\/span>
```

**Comment by jas8522** [comment]
I see 4.2.0 was released with fixes for this.

**Comment by sendtogeo** [comment]
Thanks again for checking it and finding a fix for it.

Keep in touch friend.
