### ISSUE TITLE
Regex not matched error occured while parsing search results

### ISSUE THREAD

**Issue by shaphiro** [seopanel/Seo-Panel#156]
HI, all my queries to the google search engine are returning this error from yesterday:

Regex not matched error occured while parsing search results!

Seopanel 4.2.0 version.

Query example:
`https://www.google.it/search?hl=&num=100&q=Vendita+stazioni+meteo&start=0&cr=&as_qdr=all&gws_rd=cr,ssl&nfpr=1&ie=utf-8&pws=0&gl=`

Regex:
`<div.*?class="?g.*?>.*?<div.*?class="r"*?>.*?<a href="(.*?)".*?>.*?<span.*?>(.*?)<\/span><\/h3>`

Thanks in advance.

**Comment by sendtogeo** [comment]
Thanks for updating it.

We have released patch for seo panel 4.2.0 with quick fixes

It will fix following issues

1) Google keyword rank position issue

Please check below blog link to apply the fix.

https://www.seopanel.org/blog/2019/12/seo-panel-4-2-0-patch-google-search-position-quick-fix/

If you need any help with it, Please contact us.

**Comment by jas8522** [comment]
Thanks for the fix! Worked here.

**Comment by sendtogeo** [comment]
Thanks @jas8522  for confirming it :)

**Comment by shaphiro** [comment]
It works again! Thanks

**Comment by sendtogeo** [comment]
@shaphiro  Thanks bro :+1:

**Comment by shaphiro** [comment]
Hi, the problem arose again with 4.7 version.

My regex for www.google.it is: 

`<div.*?class="?g.*?>.*?<div.*?class="r"*?>.*?<a href="(.*?)".*?>.*?<h3.*?>(.*?)<\/h3>`

Any patch available?

Thank you.

**Comment by sendtogeo** [comment]
Hi Etienne,

Thanks for reporting it.

Please use the following link to fix this issue.

https://www.seopanel.org/blog/2020/10/how-to-fix-regex-not-matched-issue-in-seo-panel-2/


Regards,
Geo Varghese <http://www.seofreetools.net>
