### ISSUE TITLE
Typo on new project screen

### ISSUE THREAD

**Issue by aliendev** [seopanel/Seo-Panel#165]
On the new project screen, when adding a new website to site auditor, in the second to the last item in the menu, "Check broken links in a page.*", the note under the selection has a typo. 

The note says:
```text
Note: Check brocken links will increase the execution time of a project.
```

The word "brocken" should be "broken"
```text
Note: Check broken links will increase the execution time of a project.
```

**Comment by aliendev** [comment]
Screenshot of the issue
![Screen Shot 2020-01-21 at 2 35 30 PM](https://user-images.githubusercontent.com/682868/72841817-c94ac600-3c5c-11ea-8b19-680108956bc0.png)

**Comment by sendtogeo** [comment]
Hi Michael,

Thanks for finding it. I have fixed it in translation tool.

It will be fixed in next version of seo panel.
