### ISSUE TITLE
add LinkedIn to social media links

### ISSUE THREAD

**Issue by aliendev** [seopanel/Seo-Panel#167]
A lot of corporate businesses rely on LinkedIn to discuss and promote brand, leadership, and recruitment. 

## Goal
Add LinkedIn to the list of options for social media checker

**Comment by sendtogeo** [comment]
Hi Michael,

Thanks for the suggestion.

Actually we try to add it along with others, but it had some issues to crawl it.

Do you know programming?

If you can add it, I can release it with next version of seo panel.

**Comment by sendtogeo** [comment]
Integrated with latest version of seo panel
