### ISSUE TITLE
Having trouble google settings

### ISSUE THREAD

**Issue by gl1tchw1tch** [seopanel/Seo-Panel#182]
I cannot get the connection to verify, I’ve followed each step.
![IMG_9838](https://user-images.githubusercontent.com/22322858/84081453-f7cb0280-a9ab-11ea-8bbb-c1e5055e7fad.jpeg)
![IMG_9839](https://user-images.githubusercontent.com/22322858/84081495-0f09f000-a9ac-11ea-903f-0c430666d0f4.jpeg)
![IMG_9840](https://user-images.githubusercontent.com/22322858/84081541-2812a100-a9ac-11ea-8433-9999a04568c6.jpeg)

**Comment by sendtogeo** [comment]
Really sorry i missed your mail.

Can you please update me, Is it working now?
