### ISSUE TITLE
Sitemap always Error - ReInstalling not Solve the Issue

### ISSUE THREAD

**Issue by ndro-agus** [seopanel/Seo-Panel#195]
Error: get all sitemaps - json key is missing the refresh_token field
thats the Error..

when submit the Sitemap, always show Error.
please remove this feature, because this is useless.

note:
Google API already **Connected** in My Account > Connections

**Comment by alexsheyko** [comment]
Check row  in table user_tokens.
if refresh_token empty?

1. in Connected in My Account > Connections do disconect
2. You need create new client OAuth 2.0
https://console.developers.google.com/
3. set new Google API Client Id, and Google API Client Secret.
4. Connect

**Comment by sendtogeo** [comment]
@alexsheyko  Thanks a lot for explaining it friend :+1:
