### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by zidingz** [seopanel/Seo-Panel#226]
Hey there!

I belong to an open source security research community, and a member (@0x7zed) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by sendtogeo** [comment]
Sure Thanks.

Can you please merge request for it.

Thanks again for great support friend.

**Comment by sendtogeo** [comment]
sure thanks friend.
