### ISSUE TITLE
Keyword Position Summary shows 2 days

### ISSUE THREAD

**Issue by szepeviktor** [seopanel/Seo-Panel#26]
Could you please have Keyword Position Summary show 30 days?

https://github.com/seopanel/Seo-Panel/blob/master/controllers/report.ctrl.php#L95

2 days' data may not mean much.

**Comment by jas8522** [comment]
Agreed! This is much better with 30 days showing by default, especially since you can already see the 2 day differential if there's been any changes simply by looking in the table.

**Comment by sendtogeo** [comment]
from date changed to 7 days
to date according to user report generated or not in that day
