### ISSUE TITLE
Site auditor and handling of redirects.

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#31]
Currently, when the site auditor encounters a URL that redirects to another, it uses cURL's CURLOPT_FOLLOWLOCATION option to follow those redirects through to their destination. This is good in terms of finding the content at the destination, however it's bad in that it associates that content with the **original** URL, not the final destination URL that you reach after following all redirects.

This means that if you have a URL like mydomain.com/seo which redirects to mydomain.com/search-engine-optimization you'll end up with two links in the auditor results that have the same content and report:

mydomain.com/seo
mydomain.com/search-engine-optimization

This is bad; I believe that only the second URL should appear in the results.

The [PHP manual for curl_setopt](http://php.net/manual/en/function.curl-setopt.php) has this comment:

> When CURLOPT_FOLLOWLOCATION and CURLOPT_HEADER are both true and redirect/s have happened then the header returned by curl_exec() will contain all the headers in the redirect chain in the order they were encountered.

Therefore we could try to return the final (accurate) URL to the site auditor from the spider using this info.

Alternatively it might be simpler (and cheaper) to do a quick header check prior to the full page content retrieval, check if there's a redirect, grab the final destination URL and feed that back through to the spider.

Any suggestions as to which option is best to proceed with?

**Comment by jas8522** [comment]
I think I have an answer to this question. Originally I was planning on impelementing this check by retreiving headers when looping through each URL found on the page. The problem with this is that it would result in a large number of header requests and likely wouldn't go through the appropriate proxies (as the current getHeader function does not -- which probably should be changed).

Instead I'm planning to retreive the headers on the standard request generated by the spider, making for just a single HTTP request for each URL (which obviously goes through the appropriate proxy checking code). It'll be slightly more messy from the perspective of DB queries, but comparatively I'd rather have more DB queries than HTTP requests.

**Comment by jas8522** [comment]
I've greatly cleaned up the confusion from the "Site auditor improvements" pull request. Please check out "Handle redirects". It's also coded against the develop branch now.

**Comment by sendtogeo** [comment]
Thanks again for your support. It is okay. I am testing your changes now.

Can I get a link to test redirects?

**Comment by jas8522** [comment]
I was using https://websaversmedia.ca in the auditor. You'll see many redirects detected while completing the audit.
