### ISSUE TITLE
php mail module

### ISSUE THREAD

**Issue by sendtogeo** [seopanel/Seo-Panel#52]
The daily report that arrives by email displays Greek Chars like "¿ÏÎ¸Î¿Ï€Î±Î¹Î´Î¹ÎºÎ±" if i go to email and set UTF-8 in the settings the chars appear good though.
I guess it has something to do with the php mail module update.

**Comment by AlexanderSk** [comment]
Is there something i can do to speed it up? Would you like me to check this issue and post a solution for the next version perhaps?

**Comment by sendtogeo** [comment]
Yes sure. That will really help seo panel project. Thanks for the support.

**Comment by AlexanderSk** [comment]
Hello again, i tried to Pull a request but i do not have permissions.
Anyway the fix easy easy to do:

On file: includes/sp-common.php

function sendMail($from, $fromName, $to ,$subject,$content, $attachment = ''){
	$mail = new PHPMailer();
        //add this line after new php mailer
	$mail->CharSet = 'UTF-8';

**Comment by sendtogeo** [comment]
Great to know that you found the fix. Greta work.

Can you please create a pull request to => https://github.com/seopanel/Seo-Panel/tree/develop

**Comment by AlexanderSk** [comment]
I did create this https://github.com/sendtogeo/Seo-Panel/pull/10
but do you want a pull from master into the Develop tree perhaps?

**Comment by sendtogeo** [comment]
Please check above commit. I have added it to the develop branch.

Thanks a lot Alex for fixing it.

Please keep supporting seo panel.
