### ISSUE TITLE
Rank report emails from SEO Panel go to spam

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#67]
Spamassassin triggers this rule at a high score (2.0) when messages come from SEO Panel:

2.0 TO_NO_BRKTS_HTML_ONLY To: lacks brackets and HTML only

To help prevent this from happening, SEO Panel should send a multi-part email. The Plaintext part which is currently missing can probably just read something like: Your reports generated successfully in seo panel, click here to get your report, and link to {$DOMAIN}/seo-tools.php

**Comment by sendtogeo** [comment]
Thanks for finding it and for the great support.
It would be great if you can provide code fix for it?

**Comment by sendtogeo** [comment]
`$mail = new PHPMailer();
	$mail->CharSet = 'UTF-8';
	
	# check whether the mail send by smtp or not
	if(SP_SMTP_MAIL){
		$mail->IsSMTP();	
		$mail->SMTPAuth = true;
		$mail->Host = SP_SMTP_HOST;
		$mail->Username = SP_SMTP_USERNAME;
		$mail->Password = SP_SMTP_PASSWORD;
		$mail->Port = SP_SMTP_PORT;
	}

	$mail->From = $from;
	$mail->FromName = $fromName;
	$mail->AddAddress($to);
	$mail->WordWrap = 70;                              
	$mail->IsHTML(true);

	$mail->Subject = $subject;
	$mail->Body = $content;`

Our current code is like this.
