### ISSUE TITLE
Reports Generation Interval/Email Notification under "Schedule Reports" vs. the same config under Report Settings

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#72]
When configuring how often to generate reports and send an email notification, it's not clear what the difference is between the following:

**Reports Manager > Schedule Reports**
- Reports generation interval
- Email notification

and

**Reports Manager > Report Settings**
- System report generation interval
- Enable report email notification

It would be great if there could be some clarification as to how these very similar sounding settings affect each other. Or perhaps they are somehow duplicates of each other?

It might make more sense to try to merge these three sections:

- Schedule Reports
- Cron Command
- Report Settings

As they all have to do with configuring your reports (Schedule/Settings) and ensuring they run successfully (cron).

**Comment by sendtogeo** [comment]
Thanks for finding it. Yes it is a little bit similar. I will change the label of it.

Reports generation interval - is the right one 

System report generation interval - is currently not required. I will hide it from front end.

**Comment by jas8522** [comment]
I'm guessing the milestone on this needs to change as 3.11.0 was released without adjustment?

**Comment by sendtogeo** [comment]
> Reports Manager > Schedule Reports
> 
>     Reports generation interval
>     Email notification
> 

Is available to all users.

But below settings available to admin only. Once admin set a interval, users can not schedule less than that.

Eg: System report generation interval is 1 week, then users can schedule report generation less than 1 week. They can set as 1 week or 1 month.

> Reports Manager > Report Settings
> 
>     System report generation interval
>     Enable report email notification


Hope this will help you to understand it. Please update me.

**Comment by jas8522** [comment]
Here's a few naming suggestion changes to help make it clearer:

- "Report Settings" -> "Global Reports Settings"
- "Enable report email notification:" -> "Allow use of email notifications for reports"
- "System report generation interval" -> "Minimum Allowed Reporting Interval"

**Comment by sendtogeo** [comment]
Thanks for the inputs and I have added it in new version.
