### ISSUE TITLE
Keyword Reports and Overall Summary reports Not Working in 3.10.0

### ISSUE THREAD

**Issue by scooter7** [seopanel/Seo-Panel#75]
Hi,

I cannot get any data for the overall summary reports or for any keyword reports despite the fact that the software indicates that it is generating report data.

Thanks!

**Comment by sendtogeo** [comment]
Can you please tell me which version of seo panel you are using?

**Comment by scooter7** [comment]
3.10.0

Thanks!

*James Vineburgh, Jr., PhD* | 319-899-6620
[image: LinkedIn] <http://www.linkedin.com/in/scootervineburgh>

**Comment by sendtogeo** [comment]
oh ok.

Please provide me the link of website you have added?

or screen shot of edit website?



Regards,
Geo Varghese <http://www.seofreetools.net>

**Comment by scooter7** [comment]
Hi,

The website is

http://luminalearningsolutions.com/seo/

A screenshot (after manually running rank checking reports, etc.) is
attached.

Thanks,

*James Vineburgh, Jr., PhD* | 319-899-6620
[image: LinkedIn] <http://www.linkedin.com/in/scootervineburgh>

**Comment by sendtogeo** [comment]
Really sorry i forgot to reply this issue here

Can you please tell me is this issue still existing in your seo panel?
