### ISSUE TITLE
> php 7.0.0 Support 

### ISSUE THREAD

**Issue by Schokolader** [seopanel/Seo-Panel#81]
support for > php 7.0

**Comment by sendtogeo** [comment]
Yes it is.

Have you found any issues?

**Comment by Schokolader** [comment]
you can not install it with php higher than 7.0. That's the issue... :)

**Comment by sendtogeo** [comment]
Oh ok.

Actually we have successfully tested it on PHP Version 7.0.9

Can you please update your version.

**Comment by sendtogeo** [comment]
Fixed in previous version.

**Comment by sendtogeo** [comment]
ref: https://github.com/seopanel/Seo-Panel/issues/39
