### ISSUE TITLE
API Creating Website results in limit_error

### ISSUE THREAD

**Issue by jas8522** [seopanel/Seo-Panel#88]
I sent this to the API:

```
Array
(
    [category] => website
    [action] => createWebsite
    [name] => domain.com
    [user_id] => 8
    [url] => http://www.domain.com/
    [SP_API_KEY] => ****
    [API_SECRET] => ***
)
```

And got this back:

```
stdClass Object
(
    [response] => Error
    [error_msg] => stdClass Object
        (
            [name] => 
            [url] => 
            [limit_error] => Website count already reached the limit for this user!
        )

)

```
But I can add a website via GUI as an admin and when logged in as the user. What am I doing wrong with this API call? (The createUser call works great!)

**Comment by sendtogeo** [comment]
Its a bit of big, I have fixed it in new version 3.12.0

Actually we need to setup website count for user type in 3.11.0 Please check attached screenshot below

![seo panel user control panel for manage settings 2018-01-23 01-12-51](https://user-images.githubusercontent.com/281293/35240781-7baf559e-ffac-11e7-8abe-566a00bb1b3f.png)

Thanks again for your great support to open this issue.

**Comment by sendtogeo** [comment]
https://github.com/seopanel/Seo-Panel/commit/d190bf46188956d0cdfce3323a5defe385092b2b#diff-1d96d3be960b3e58e4bebe45087496b2

**Comment by jas8522** [comment]
Ah, yes I wondered why there didn't seem to be a way to configure the actual limits! I'll get updating to latest 'master' and test it out soon.

**Comment by sendtogeo** [comment]
Thanks. Latest commit in develop branch



Regards,
Geo Varghese <http://www.seofreetools.net>
